#
# File: module-catalog.properties
#
# Provides Quark Spin with the ability to map Java Module System Modules to the associated
# Apache Maven Artifacts containing the said module.  It allows Quark Spin to determine the possible Apache Maven
# Artifacts that are required on a Class or Module Path for compilation, testing and building modules.
#
# Each line (property) in this file consists of a Java Module System Name = Apache Maven G:A:T:C:R coordinate
# where:
#   G = groupId
#   A = artifactId
#   T = (optional) artifact type (module) eg: "jar"  (jar is assumed)
#   C = (optional) classifier
#   R = version range
#
# See: https://www.oracle.com/corporate/features/understanding-java-9-modules.html
# See: http://maven.apache.org/pom.html
#

build.spin = build.spin:spin-api:[0.0.0,)
build.spin.application = build.spin:spin:[0.0.0,)
build.spin.collider = build.spin:spin-collider:[0.0.0,)
build.spin.common = build.spin:spin-common:[0.0.0,)
build.spin.engine = build.spin:spin-engine:[0.0.0,)
build.spin.testing = build.spin:spin-testing:[0.0.0,)

build.spin.module.clean = build.spin.module:spin-clean-module:[0.0.0,)
build.spin.module.checkstyle = build.spin.module:spin-checkstyle-module:[0.0.0,)
build.spin.module.configuration = build.spin.module:spin-configuration-module:[0.0.0,)
build.spin.module.git = build.spin.module:spin-git-module:[0.0.0,)
build.spin.module.gpg = build.spin.module:spin-gpg-module:[0.0.0,)
build.spin.module.jar = build.spin.module:spin-jar-module:[0.0.0,)
build.spin.module.java = build.spin.module:spin-java-module:[0.0.0,)
build.spin.java.module.tests.main = build.spin.module:spin-java-module-tests:[0.0.0,)
build.spin.module.junit = build.spin.module:spin-junit-module:[0.0.0,)
build.spin.module.maven = build.spin.module:spin-maven-module:[0.0.0,)
build.spin.module.modulesystem = build.spin.module:spin-module-system-module:[0.0.0,)
build.spin.module.reporting = build.spin.module:spin-reporting-module:[0.0.0,)

build.base.archiving = build.base:base-archiving:[0.0.0,)
build.base.assertion = build.base:base-assertion:[0.0.0,)
build.base.commandline = build.base:base-commandline:[0.0.0,)
build.base.configuration = build.base:base-configuration:[0.0.0,)
build.base.expression = build.base:base-expression:[0.0.0,)
build.base.flow = build.base:base-flow:[0.0.0,)
build.base.version = build.base:base-version:[0.0.0,)
build.base.foundation = build.base:base-foundation:[0.0.0,)
build.base.graph = build.base:base-graph:[0.0.0,)
build.base.io = build.base:base-io:[0.0.0,)
build.base.json = build.base:base-json:[0.0.0,)
build.base.logging = build.base:base-logging:[0.0.0,)
build.base.marshalling = build.base:base-marshalling:[0.0.0,)
build.base.mereology = build.base:base-mereology:[0.0.0,)
build.base.naming = build.base:base-naming:[0.0.0,)
build.base.network = build.base:base-network:[0.0.0,)
build.base.option = build.base:base-option:[0.0.0,)
build.base.parsing = build.base:base-parsing:[0.0.0,)
build.base.query = build.base:base-query:[0.0.0,)
build.base.retryable = build.base:base-retryable:[0.0.0,)
build.base.table = build.base:base-table:[0.0.0,)
build.base.tar = build.base:base-tar:[0.0.0,)
build.base.telemetry = build.base:base-telemetry:[0.0.0,)
build.base.telemetry.foundation = build.base:base-telemetry-foundation:[0.0.0,)
build.base.template = build.base:base-template:[0.0.0,)
build.base.template.processor = build.base:base-template-processor:[0.0.0,)
build.base.transport = build.base:base-transport:[0.0.0,)
build.base.transport.json = build.base:base-transport-json:[0.0.0,)

build.codemodel.expression = build.codemodel:codemodel-expression:[0.0.0,)
build.codemodel.foundation = build.codemodel:codemodel-foundation:[0.0.0,)
build.codemodel.framework = build.codemodel:codemodel-framework:[0.0.0,)
build.codemodel.hierarchical = build.codemodel:codemodel-hierarchical:[0.0.0,)
build.codemodel.imperative = build.codemodel:codemodel-imperative:[0.0.0,)
build.codemodel.dependency.injection = build.codemodel:codemodel-dependency-injection:[0.0.0,)
build.codemodel.jdk = build.codemodel:codemodel-jdk:[0.0.0,)
build.codemodel.objectoriented = build.codemodel:codemodel-objectoriented:[0.0.0,)

build.percolate.core = build.percolate:percolate-core:[0.0.0,)

build.spawn.application = build.spawn:spawn-application:[0.0.0,)
build.spawn.jdk = build.spawn:spawn-jdk:[0.0.0,)
build.spawn.option = build.spawn:spawn-option:[0.0.0,)
build.spawn.platform.local = build.spawn:spawn-local-platform:[0.0.0,)
build.spawn.platform.local.jdk = build.spawn:spawn-local-jdk:[0.0.0,)

com.fasterxml.jackson.annotation = com.fasterxml.jackson.core:jackson-annotations:[0.0.0,)
com.fasterxml.jackson.core = com.fasterxml.jackson.core:jackson-core:[0.0.0,)
com.fasterxml.jackson.databind = com.fasterxml.jackson.core:jackson-databind:[0.0.0,)

jakarta.el = jakarta.el:jakarta.el-api:[4.0.0,)
jakarta.inject = jakarta.inject:jakarta.inject-api:[2.0.1,)

javax.inject = javax.inject:javax.inject:[0.0.0,)

org.assertj.core = org.assertj:assertj-core:jar:3.27.7

org.junit.jupiter.api = org.junit.jupiter:junit-jupiter-api:6.0.3

org.jspecify = org.jspecify:jspecify:[1.0.0,)

org.mockito = org.mockito:mockito-core:jar:5.23.0

org.reactivestreams = org.reactivestreams:reactive-streams:[1.0.3,)
