#
# File: version.properties
#
# Defines the version information for each Java Module System modules.   This allows Quark Spin to determine the
# version of Apache Maven Artifacts to retrieve for establishing Class and Module Paths when compiling, testing and
# building a module.
#
# Each property name is a GLOB pattern (to match a Java Module name), followed by = and then property value, which is
# the Apache Maven Version number.
#
# The use of GLOB patterns permit similarly defined module names, typically from a single developer/organization, to
# share the same module version (as they commonly do).
#
# See: https://en.wikipedia.org/wiki/Glob_(programming)
# See: http://maven.apache.org/pom.html
#
# NOTE: Lookup and use of this file is not yet supported (coming soon!)
#

jakarta.inject = 2.0.1
jakarta.el = 6.0.1

build.spin = 0.5.0
build.spin.* = 0.5.0

build.base.* = 0.31.0
build.codemodel.* = 0.28.0
build.percolate.* = 0.2.2
build.spawn.* = 0.4.2

com.fasterxml.jackson.annotations = 2.21
com.fasterxml.jackson.databind = 2.21.2

org.assertj.core = 3.27.7

org.junit.jupiter.* = 6.0.3

org.mockito* = 5.23.0
